name: CI / CD
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd webApp
      - name: Test with pytest
        run: |
          python3 -m pytest

  push_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $USERNAME -p $PASSWORD
      - name: Build
        run: docker build ./webApp --file Dockerfile --tag nmeng01/kiwi-swefinal:${{ github.sha }}
      - name: Push
        run: docker push nmeng01/kiwi-swefinal:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker
        run: sudo apt-get update && sudo apt-get install -y docker-compose
      - name: Build and Deploy
        run: docker-compose up --build -d
      - name: Deploy Flask app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            echo 'Deployment successful to digital ocean'